//setting the parameters to run the generatePassword function....
const uppercaseCharCodes = arrayFromLowToHigh(65, 90); //this creates an array with all uppercase values in ASCII chart
const lowercaseCharCodes = arrayFromLowToHigh(97, 122); //this creates an array with all lowercase values in ASCII chart
const numberCharCodes = arrayFromLowToHigh(48, 57); // this creates an array with all number values in ASCII chart
const symbolCharCodes = arrayFromLowToHigh(33, 47).concat(arrayFromLowToHigh(58, 64)).concat(arrayFromLowToHigh(91, 96)).concat(arrayFromLowToHigh(123,126)); // this combines the different sections of arrays into one for symbols



// sets a variable to the Generate Password button in index.html
var generateBtn = document.querySelector("#generate");

// Add event listener to generate button to look for a click on the generate button then runs the writePassword function
generateBtn.addEventListener("click", writePassword);






// Write password to the #password input using value generated by generatePassword function
function writePassword() {

  var password = generatePassword();
  var passwordText = document.querySelector("#password");
  passwordText.value = password;
}



// creates an array that goes from the low number to high number inserted for setting character tables inside of generatePassword function
function arrayFromLowToHigh(low, high) {
  const array = [];
  for (let i = low; i <= high; i++) {
    array.push(i)
  }
  return array;
}



// function to take inputs from user and generate a password.
function generatePassword() {

var characterAmount = parseInt(window.prompt("How many characters do you want? Please choose between 8 and 128."));
        
    // this ensures they enter a valid number between 8 and 128
        if (Number.isNaN(characterAmount)) {
        alert("Please pick a number.");
        generatePassword();
      } else if (characterAmount < 8 || characterAmount > 128) {
        alert("Password length must be between 8 and 128 characters.")
        generatePassword();
      }

  
      
var includeUpper = confirm("Would you like to include uppercase letters? Cancel for no.");
var includeNumber = confirm("Would you like to include numbers? Cancel for no.");
var includeSymbol  = confirm("Would you like to include symbols? Cancel for no.");

var charCodes = lowercaseCharCodes;     //default is at least lowercase letters only.
var randomPassword = []; //sets an array for the password characters after using ascii codes    

  // this series of if statements set the different values of the potential charCodes array
  if (includeUpper === true) {
    charCodes = charCodes.concat(uppercaseCharCodes);
  }

  if (includeNumber === true) {
    charCodes = charCodes.concat(numberCharCodes);
  }

  if (includeSymbol === true) {
    charCodes = charCodes.concat(symbolCharCodes);
  }

  //this loops through the array for the number of characters you want in password. character is found by random with math function
  for (let i = 0; i < characterAmount; i++) {
    const characterCode = charCodes[Math.floor(Math.random() * charCodes.length)];

    randomPassword.push(String.fromCharCode(characterCode));
  }

  //this returns the password 
  return randomPassword.join('');

}




